vim.keymap.set({'n','v'}, '<leader>t', '<Cmd>Neotree toggle<CR>')
vim.keymap.set({'n', 'v'}, '<C-n>', '<Cmd>Neotree toggle<CR>')
vim.keymap.set({'n', 'v'}, '<leader>fh', '<C-w>h')
vim.keymap.set({'n', 'v'}, '<leader>fl', '<C-w>l')
vim.keymap.set({'n', 'v'}, '<leader>ft', '<Cmd>Neotree focus<CR>')
